### ISSUE TITLE
Parsing code from URL

### ISSUE THREAD

**Issue by Gene-Dana** [TesteurManiak/flutter_web_twitch_auth#1] opened 2021-04-03 07:09 UTC
Hi there ! I appreciate the work you have done ! I've went through both branches and had mixed results ! I thought the second example may be more elegant, but it did not run for me ! 

Honestly, I've heard from Users that they prefer the no popup, and I'm wondering if there is a way to pull URL parameters from the html.window ! 

I'm abstracting this to github_sign_in and they make you jump an extra hoop with first by getting a code to use for the access token.

Is there a better way to handle this? I would really like to sort this out

**Comment by TesteurManiak** [comment] 2021-04-03 08:25
Hi, I don't know how you have tried to implement the "popup example" but I have made an [article on medium](https://itnext.io/flutter-web-oauth-authentication-through-external-window-d890a7ff6463) to explain the steps in details.

About github_sign_in I am not sure to have understood your issue, did what you mean was that github needs first to get a code which you will be using to request the access token so you need to grab a code from your application's url 2 times (first the code then the token) ?

**Comment by Gene-Dana** [comment] 2021-04-03 13:19
> (first the code then the token) ?

Yes! and that entails parsing down the actual HTML for this code to then use for the access token.

![image](https://user-images.githubusercontent.com/45580241/113479533-ac637280-945d-11eb-86dd-b6c012cca743.png)
https://docs.github.com/en/developers/apps/authorizing-oauth-apps


I've scratched my head quite a bit attempting to do that !

**Comment by TesteurManiak** [comment] 2021-04-03 16:40
Well this is a classic authentication flow, you can grab the code from the URL the same way it is done in this repo then perform a POST request using an HTTP client to fetch the OAuth token, the token will be in the response not in the URL.

**Comment by Gene-Dana** [comment] 2021-04-05 17:08
> Well this is a classic authentication flow, you can grab the code from the URL the same way it is done in this repo then perform a POST request using an HTTP client to fetch the OAuth token, the token will be in the response not in the URL.

I tried super hard this weekend to solve how to grab the code from the URL. The HTML package did not seem to have that functionality and I felt like it should

**Comment by TesteurManiak** [comment] 2021-04-05 18:43
This is what I'm doing in this example:
```dart
    final currentUrl = Uri.base;
    if (!currentUrl.fragment.contains('access_token=')) {
      // You are not connected so redirect to the Twitch authentication page.
      WidgetsBinding.instance.addPostFrameCallback((_) {
        html.window.location.assign(
          'https://id.twitch.tv/oauth2/authorize?response_type=token&client_id=$clientId&redirect_uri=${currentUrl.origin}&scope=viewing_activity_read',
        );
      });
    } else {
      // You are connected, you can grab the code from the url.
      final fragments = currentUrl.fragment.split('&');
      _token = fragments
          .firstWhere((e) => e.startsWith('access_token='))
          .substring('access_token='.length);
      WidgetsBinding.instance
          .addPostFrameCallback((_) => setState(() => _showUserData = true));
    }
```

Calling `Uri.base` let you grab your application's current URL, in this specific sample I'm checking on launch the URL to check if the code is inside it. (Note that I am getting the code from the URL fragments which might be specific to Twitch's API)

**Comment by Gene-Dana** [comment] 2021-04-06 14:32
Yes, fragments are not standard for every API. There other challenge was this : This code relies on the return of an access token, in which the URI is https://localhost:8080/#accesstoken=...

The return from the Github API is not an access token, it is a code, in which the URI is https://localhost:8080/#?code=...

Notice the '?'

Whatever the case, when I print out the URI, it does not recognize this new address, and it just goes in an endless loop of requesting a code ! 
![2021-04-03 00 30 48](https://user-images.githubusercontent.com/45580241/113727674-57c13100-96c3-11eb-8346-635832dbe562.gif)

Does the '?' signify that it is a http request?

**Comment by TesteurManiak** [comment] 2021-04-06 14:54
No the '?' is a separator for a Query string added when redirecting to your redirection Url with the code.
Here is a StackOverflow answer explaining it: https://stackoverflow.com/a/33041515/9942346

In your case you would be looking into the `Uri.base.queryParameters`.

You should be able to grab the code like this.

```dart
final currentUrl = Uri.base;
if (currentUrl.queryParameters.containsKey('code')) {
  final code = currentUrl.queryParameters.containsKey['code'];
}
```
I'm assuming that you're looping because you don't manage to get your code. If that's not the case, please provide a minimal reproducible example.

**Comment by Gene-Dana** [comment] 2021-04-06 16:43
I greatly appreciate your help ! I made a reproducible example here ! https://github.com/Gene-Dana/flutter_web_twitch_auth

According to the prints, the URI does not have any query params !

**Comment by TesteurManiak** [comment] 2021-04-06 17:56
Okay tested your code, it seems you are correct your code is not detected in the URL. I don't really know why so for the time being you might want to login using an external popup to manage the authentication and grab the code.

Here is a code sample you could use:

```dart
void _login(String data) {
    /// Parse data to extract the token.
    final receivedUri = Uri.parse(data);

    /// Close the popup window
    if (_popupWin != null) {
      _popupWin!.close();
      _popupWin = null;
    }

    setState(() => _token = receivedUri.queryParameters['code']);
  }

  @override
  void initState() {
    super.initState();

    /// Listen to message send with `postMessage`.
    html.window.onMessage.listen((event) {
      /// The event contains the token which means the user is connected.
      if (event.data.toString().contains('code=')) {
        _login(event.data);
      }
    });

    /// You are not connected so open the Twitch authentication page.
    WidgetsBinding.instance!.addPostFrameCallback((_) {
      final authUrl =
          'https://github.com/login/oauth/authorize?client_id=$clientId&scope=user,gist,user:email';
      _popupWin = html.window.open(
          authUrl, "Twitch Auth", "width=800, height=900, scrollbars=yes");
    });
  }
``` 

To work properly you will need to add a file `static.html` in your `web/` folder (you can find the file I use [here](https://github.com/TesteurManiak/flutter_web_twitch_auth/blob/use-external-win/lib/main.dart)) and do not forget to change your URL redirection to `http://localhost:5000/static.html`.

**Comment by Gene-Dana** [comment] 2021-04-06 19:30
Yes, I greatly appreciate this. If you have any ideas on why this is not working, I would love to hear them !

**Comment by Gene-Dana** [comment] 2021-04-07 02:51
> Okay tested your code, it seems you are correct your code is not detected in the URL. I don't really know why so for the time being you might want to login using an external popup to manage the authentication and grab the code.

It could be because we are looking for the URI onInit - not sure how kosher it is.

or it could be that this is a get request.

im interested in understanding it and again greatly appreciate your help

**Closed as completed** 2021-09-12 12:06 UTC
